/**
 * @license
 * abbozza!
 *
 * Copyright 2015 Michael Brinkmeier ( michael.brinkmeier@uni-osnabrueck.de )
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview This file defines the code generated by the blocks.
 * 
 * Each code template is given in the follwoing form
 * 
 * Abbozza.Code[type] = [ <template> , [ <arg1>, <arg2>, ...] ]
 *  
 * @author michael.brinkmeier@uni-osnabrueck.de (Michael Brinkmeier)
 */


AbbozzaCode= [];

AbbozzaCode['cond_if'] = [ 'if (#) {\n#\n}', [ "V_CONDITION" , "S_STATEMENTS"] ];
AbbozzaCode['cond_if_else'] = [ 'if (#) {\n#\n} else {\n#\n}', [ "V_CONDITION" , "S_STATEMENTS1" , "S_STATEMENTS2" ] ];


AbbozzaCode['math_number'] = [ "#", ["F_VALUE"] ];
AbbozzaCode['math_calc'] = [ "#", [ Abbozza.MathCalc._generateCode ]];
AbbozzaCode['math_round'] = [ "#", [ Abbozza.MathRound._generateCode ]];
AbbozzaCode['math_unary'] = [ "#", [ Abbozza.MathUnary._generateCode ]];
AbbozzaCode['math_binary'] = [ "#", [ Abbozza.MathBinary._generateCode ]];
AbbozzaCode['math_random'] = [ "#", [ Abbozza.MathRandom._generateCode ]];
AbbozzaCode['math_random2'] = [ "#", [ Abbozza.MathRandom2._generateCode ]];
AbbozzaCode['math_randomseed'] = [ "randomSeed(#);", [ "V_SEED" ]];
AbbozzaCode['math_millis'] = [ "millis()", [] ];

